- name: Deploy Flask App
  hosts: instance_1
  become: true
  vars_files:
    - ./store.yml

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - python3.13
          - python3.13-venv
          - git
        state: present
        update_cache: yes

    - name: Create app directory
      file:
        path: /var/www/groceryflow
        state: directory
        owner: www-data
        group: www-data
        mode: 0755

    - name: Synchronize project files
      synchronize:
        src: /home/jake/Code/project-recipe/src
        dest: /var/www/groceryflow/

    - name: Synchronize tex files
      synchronize:
        src: /home/jake/Code/project-recipe/files
        dest: /var/www/groceryflow/

    - name: Synchronize recipe files
      synchronize:
        src: /home/jake/Code/project-recipe/recipes
        dest: /var/www/groceryflow/

    - name: Synchronize requirements.txt
      synchronize:
        src: /home/jake/Code/project-recipe/requirements.txt
        dest: /var/www/groceryflow/

    - name: Set ownership and permissions
      file:
        path: /var/www/groceryflow
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Create virtual environment
      command: python3.13 -m venv /var/www/groceryflow/venv
      args:
        creates: /var/www/groceryflow/venv

    - name: Install dependencies
      command: /var/www/groceryflow/venv/bin/pip install -r /var/www/groceryflow/requirements.txt
      args:
        chdir: /var/www/groceryflow

    - name: Configure systemd service
      copy:
        dest: /etc/systemd/system/groceryflow.service
        content: |
          [Unit]
          Description=Gunicorn instance to serve groceryflow
          After=network.target

          [Service]
          User=www-data
          Group=www-data
          WorkingDirectory=/var/www/groceryflow
          Environment="PATH=/var/www/groceryflow/venv/bin"
          Environment="PYTHONPATH=/var/www/groceryflow/src"
          Environment="RECIPE_DIR=/var/www/groceryflow/recipes"
          Environment="SESSION_KEY={{SESSION_KEY}}"
          Environment="FILE_GEN_OUTPUT_DIR=/tmp/files"
          ExecStart=/var/www/groceryflow/venv/bin/gunicorn --workers 1 --bind unix:/var/www/groceryflow/groceryflow.sock -m 007 src.main:app

          [Install]
          WantedBy=multi-user.target
      notify: restart flask app

    - name: Start Flask app
      systemd:
        name: groceryflow
        state: started
        enabled: true

  handlers:
    - name: restart flask app
      systemd:
        name: groceryflow
        state: restarted
